name: Tests
on: [push, pull_request]

jobs:
  test-ubuntu-ruby:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:${{matrix.mysql}}
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: trilogis_adapter_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        ruby: ['3.1', '3.0', '2.7']
        mysql: ['8.0']
    steps:
      - name: Set Up Actions
        uses: actions/checkout@v2
      - name: Install GEOS
        run: sudo apt-get install libgeos-dev
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create Database
        run: |
          mysql -uroot -h127.0.0.1 -ppassword -e 'CREATE DATABASE IF NOT EXISTS trilogis_adapter_test;'
          mysql -uroot -h127.0.0.1 -ppassword -e 'CREATE DATABASE IF NOT EXISTS trilogis_tasks_test;'
      - name: Run Tests
        run: bundle exec rake test
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PASSWORD: password
